name: Sync to Hugging Face hub
on:
  push:
    branches: [huggingFace]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Track large files with Git LFS
        run: git lfs track "presentation.pptx"

      - name: Add and commit files
        run: |
          git add .
          git commit -m "Add presentation.pptx using Git LFS"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://mirukulla:$HF_TOKEN@huggingface.co/spaces/mirukulla/Resonate
